name: CI Tests
env:
  NODE_VERSION: 20
on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  executing-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node.js Version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@staffbase'

      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.STAFFBOT_NPM_READ }}" >> .npmrc

      - name: Install Yarn Dependencies
        working-directory:  samples/weather-forecast
        run: yarn install --frozen-lockfile

      - name: Run Build
        working-directory: samples/weather-forecast
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: yarn build

      - name: Run Lint
        working-directory: samples/weather-forecast
        run: yarn lint

      - name: Run Type check
        working-directory: samples/weather-forecast
        run: yarn type-check

      - name: Run Tests
        working-directory: samples/weather-forecast
        run: yarn test
